name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: recursive
        repository: oscarkremer/oscarkremer.github.io
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
    - uses: actions/jekyll-build-pages@v1
    - name: Build the site in the jekyll/builder container
      run:  tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        path: ./artifact.tar
        if-no-files-found: warn
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Dep the site in the jekyll/builder container
      uses: actions/deploy-pages@v1      
      with: 
          timeout: 600000
          error_count: 10
          reporting_interval: 1000
          github_token: ${{ secrets.GITHUB_TOKEN }}
