name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/jekyll-build-pages@v1
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: recursive
        repository: oscarkremer/oscarkremer.github.io
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
    - name: Build page with Jekyll
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        path: ./artifact.tar
        if-no-files-found: warn
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"